// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package ru.sberbank.jmh.dto;

public final class ProtoDTO {
  private ProtoDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FullOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.sberbank.jmh.Full)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fullName = 1;</code>
     * @return Whether the fullName field is set.
     */
    boolean hasFullName();
    /**
     * <code>required string fullName = 1;</code>
     * @return The fullName.
     */
    java.lang.String getFullName();
    /**
     * <code>required string fullName = 1;</code>
     * @return The bytes for fullName.
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    /**
     * <code>required uint32 fullSize = 2;</code>
     * @return Whether the fullSize field is set.
     */
    boolean hasFullSize();
    /**
     * <code>required uint32 fullSize = 2;</code>
     * @return The fullSize.
     */
    int getFullSize();

    /**
     * <code>repeated double fullList = 3;</code>
     * @return A list containing the fullList.
     */
    java.util.List<java.lang.Double> getFullListList();
    /**
     * <code>repeated double fullList = 3;</code>
     * @return The count of fullList.
     */
    int getFullListCount();
    /**
     * <code>repeated double fullList = 3;</code>
     * @param index The index of the element to return.
     * @return The fullList at the given index.
     */
    double getFullList(int index);

    /**
     * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
     * @return Whether the part field is set.
     */
    boolean hasPart();
    /**
     * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
     * @return The part.
     */
    ProtoDTO.Full.Part getPart();
    /**
     * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
     */
    ProtoDTO.Full.PartOrBuilder getPartOrBuilder();
  }
  /**
   * Protobuf type {@code ru.sberbank.jmh.Full}
   */
  public static final class Full extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.sberbank.jmh.Full)
      FullOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Full.newBuilder() to construct.
    private Full(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Full() {
      fullName_ = "";
      fullList_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Full();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Full(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fullName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fullSize_ = input.readUInt32();
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                fullList_ = newDoubleList();
                mutable_bitField0_ |= 0x00000004;
              }
              fullList_.addDouble(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                fullList_ = newDoubleList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                fullList_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              ProtoDTO.Full.Part.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = part_.toBuilder();
              }
              part_ = input.readMessage(ProtoDTO.Full.Part.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(part_);
                part_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          fullList_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoDTO.internal_static_ru_sberbank_jmh_Full_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoDTO.internal_static_ru_sberbank_jmh_Full_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoDTO.Full.class, ProtoDTO.Full.Builder.class);
    }

    public interface PartOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ru.sberbank.jmh.Full.Part)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string partName = 1;</code>
       * @return Whether the partName field is set.
       */
      boolean hasPartName();
      /**
       * <code>required string partName = 1;</code>
       * @return The partName.
       */
      java.lang.String getPartName();
      /**
       * <code>required string partName = 1;</code>
       * @return The bytes for partName.
       */
      com.google.protobuf.ByteString
          getPartNameBytes();

      /**
       * <code>required double partSize = 2;</code>
       * @return Whether the partSize field is set.
       */
      boolean hasPartSize();
      /**
       * <code>required double partSize = 2;</code>
       * @return The partSize.
       */
      double getPartSize();

      /**
       * <code>repeated uint32 partList = 3;</code>
       * @return A list containing the partList.
       */
      java.util.List<java.lang.Integer> getPartListList();
      /**
       * <code>repeated uint32 partList = 3;</code>
       * @return The count of partList.
       */
      int getPartListCount();
      /**
       * <code>repeated uint32 partList = 3;</code>
       * @param index The index of the element to return.
       * @return The partList at the given index.
       */
      int getPartList(int index);
    }
    /**
     * Protobuf type {@code ru.sberbank.jmh.Full.Part}
     */
    public static final class Part extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ru.sberbank.jmh.Full.Part)
        PartOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Part.newBuilder() to construct.
      private Part(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Part() {
        partName_ = "";
        partList_ = emptyIntList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Part();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Part(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                partName_ = bs;
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                partSize_ = input.readDouble();
                break;
              }
              case 24: {
                if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                  partList_ = newIntList();
                  mutable_bitField0_ |= 0x00000004;
                }
                partList_.addInt(input.readUInt32());
                break;
              }
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                  partList_ = newIntList();
                  mutable_bitField0_ |= 0x00000004;
                }
                while (input.getBytesUntilLimit() > 0) {
                  partList_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) != 0)) {
            partList_.makeImmutable(); // C
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoDTO.internal_static_ru_sberbank_jmh_Full_Part_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoDTO.internal_static_ru_sberbank_jmh_Full_Part_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoDTO.Full.Part.class, ProtoDTO.Full.Part.Builder.class);
      }

      private int bitField0_;
      public static final int PARTNAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object partName_;
      /**
       * <code>required string partName = 1;</code>
       * @return Whether the partName field is set.
       */
      @java.lang.Override
      public boolean hasPartName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string partName = 1;</code>
       * @return The partName.
       */
      @java.lang.Override
      public java.lang.String getPartName() {
        java.lang.Object ref = partName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            partName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string partName = 1;</code>
       * @return The bytes for partName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPartNameBytes() {
        java.lang.Object ref = partName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PARTSIZE_FIELD_NUMBER = 2;
      private double partSize_;
      /**
       * <code>required double partSize = 2;</code>
       * @return Whether the partSize field is set.
       */
      @java.lang.Override
      public boolean hasPartSize() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double partSize = 2;</code>
       * @return The partSize.
       */
      @java.lang.Override
      public double getPartSize() {
        return partSize_;
      }

      public static final int PARTLIST_FIELD_NUMBER = 3;
      private com.google.protobuf.Internal.IntList partList_;
      /**
       * <code>repeated uint32 partList = 3;</code>
       * @return A list containing the partList.
       */
      @java.lang.Override
      public java.util.List<java.lang.Integer>
          getPartListList() {
        return partList_;
      }
      /**
       * <code>repeated uint32 partList = 3;</code>
       * @return The count of partList.
       */
      public int getPartListCount() {
        return partList_.size();
      }
      /**
       * <code>repeated uint32 partList = 3;</code>
       * @param index The index of the element to return.
       * @return The partList at the given index.
       */
      public int getPartList(int index) {
        return partList_.getInt(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasPartName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPartSize()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, partName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeDouble(2, partSize_);
        }
        for (int i = 0; i < partList_.size(); i++) {
          output.writeUInt32(3, partList_.getInt(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, partName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, partSize_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < partList_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeUInt32SizeNoTag(partList_.getInt(i));
          }
          size += dataSize;
          size += 1 * getPartListList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoDTO.Full.Part)) {
          return super.equals(obj);
        }
        ProtoDTO.Full.Part other = (ProtoDTO.Full.Part) obj;

        if (hasPartName() != other.hasPartName()) return false;
        if (hasPartName()) {
          if (!getPartName()
              .equals(other.getPartName())) return false;
        }
        if (hasPartSize() != other.hasPartSize()) return false;
        if (hasPartSize()) {
          if (java.lang.Double.doubleToLongBits(getPartSize())
              != java.lang.Double.doubleToLongBits(
                  other.getPartSize())) return false;
        }
        if (!getPartListList()
            .equals(other.getPartListList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasPartName()) {
          hash = (37 * hash) + PARTNAME_FIELD_NUMBER;
          hash = (53 * hash) + getPartName().hashCode();
        }
        if (hasPartSize()) {
          hash = (37 * hash) + PARTSIZE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getPartSize()));
        }
        if (getPartListCount() > 0) {
          hash = (37 * hash) + PARTLIST_FIELD_NUMBER;
          hash = (53 * hash) + getPartListList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoDTO.Full.Part parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoDTO.Full.Part parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoDTO.Full.Part parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoDTO.Full.Part parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoDTO.Full.Part parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoDTO.Full.Part parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoDTO.Full.Part parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoDTO.Full.Part parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoDTO.Full.Part parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoDTO.Full.Part parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoDTO.Full.Part parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoDTO.Full.Part parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoDTO.Full.Part prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ru.sberbank.jmh.Full.Part}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ru.sberbank.jmh.Full.Part)
          ProtoDTO.Full.PartOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoDTO.internal_static_ru_sberbank_jmh_Full_Part_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoDTO.internal_static_ru_sberbank_jmh_Full_Part_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoDTO.Full.Part.class, ProtoDTO.Full.Part.Builder.class);
        }

        // Construct using ru.sberbank.jmh.dto.ProtoDTO.Full.Part.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          partName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          partSize_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          partList_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoDTO.internal_static_ru_sberbank_jmh_Full_Part_descriptor;
        }

        @java.lang.Override
        public ProtoDTO.Full.Part getDefaultInstanceForType() {
          return ProtoDTO.Full.Part.getDefaultInstance();
        }

        @java.lang.Override
        public ProtoDTO.Full.Part build() {
          ProtoDTO.Full.Part result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ProtoDTO.Full.Part buildPartial() {
          ProtoDTO.Full.Part result = new ProtoDTO.Full.Part(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.partName_ = partName_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.partSize_ = partSize_;
            to_bitField0_ |= 0x00000002;
          }
          if (((bitField0_ & 0x00000004) != 0)) {
            partList_.makeImmutable();
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.partList_ = partList_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoDTO.Full.Part) {
            return mergeFrom((ProtoDTO.Full.Part)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoDTO.Full.Part other) {
          if (other == ProtoDTO.Full.Part.getDefaultInstance()) return this;
          if (other.hasPartName()) {
            bitField0_ |= 0x00000001;
            partName_ = other.partName_;
            onChanged();
          }
          if (other.hasPartSize()) {
            setPartSize(other.getPartSize());
          }
          if (!other.partList_.isEmpty()) {
            if (partList_.isEmpty()) {
              partList_ = other.partList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePartListIsMutable();
              partList_.addAll(other.partList_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasPartName()) {
            return false;
          }
          if (!hasPartSize()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoDTO.Full.Part parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoDTO.Full.Part) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object partName_ = "";
        /**
         * <code>required string partName = 1;</code>
         * @return Whether the partName field is set.
         */
        public boolean hasPartName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string partName = 1;</code>
         * @return The partName.
         */
        public java.lang.String getPartName() {
          java.lang.Object ref = partName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              partName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string partName = 1;</code>
         * @return The bytes for partName.
         */
        public com.google.protobuf.ByteString
            getPartNameBytes() {
          java.lang.Object ref = partName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            partName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string partName = 1;</code>
         * @param value The partName to set.
         * @return This builder for chaining.
         */
        public Builder setPartName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          partName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string partName = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearPartName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          partName_ = getDefaultInstance().getPartName();
          onChanged();
          return this;
        }
        /**
         * <code>required string partName = 1;</code>
         * @param value The bytes for partName to set.
         * @return This builder for chaining.
         */
        public Builder setPartNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          partName_ = value;
          onChanged();
          return this;
        }

        private double partSize_ ;
        /**
         * <code>required double partSize = 2;</code>
         * @return Whether the partSize field is set.
         */
        @java.lang.Override
        public boolean hasPartSize() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required double partSize = 2;</code>
         * @return The partSize.
         */
        @java.lang.Override
        public double getPartSize() {
          return partSize_;
        }
        /**
         * <code>required double partSize = 2;</code>
         * @param value The partSize to set.
         * @return This builder for chaining.
         */
        public Builder setPartSize(double value) {
          bitField0_ |= 0x00000002;
          partSize_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double partSize = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPartSize() {
          bitField0_ = (bitField0_ & ~0x00000002);
          partSize_ = 0D;
          onChanged();
          return this;
        }

        private com.google.protobuf.Internal.IntList partList_ = emptyIntList();
        private void ensurePartListIsMutable() {
          if (!((bitField0_ & 0x00000004) != 0)) {
            partList_ = mutableCopy(partList_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @return A list containing the partList.
         */
        public java.util.List<java.lang.Integer>
            getPartListList() {
          return ((bitField0_ & 0x00000004) != 0) ?
                   java.util.Collections.unmodifiableList(partList_) : partList_;
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @return The count of partList.
         */
        public int getPartListCount() {
          return partList_.size();
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @param index The index of the element to return.
         * @return The partList at the given index.
         */
        public int getPartList(int index) {
          return partList_.getInt(index);
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @param index The index to set the value at.
         * @param value The partList to set.
         * @return This builder for chaining.
         */
        public Builder setPartList(
            int index, int value) {
          ensurePartListIsMutable();
          partList_.setInt(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @param value The partList to add.
         * @return This builder for chaining.
         */
        public Builder addPartList(int value) {
          ensurePartListIsMutable();
          partList_.addInt(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @param values The partList to add.
         * @return This builder for chaining.
         */
        public Builder addAllPartList(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensurePartListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, partList_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated uint32 partList = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearPartList() {
          partList_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ru.sberbank.jmh.Full.Part)
      }

      // @@protoc_insertion_point(class_scope:ru.sberbank.jmh.Full.Part)
      private static final ProtoDTO.Full.Part DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoDTO.Full.Part();
      }

      public static ProtoDTO.Full.Part getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Part>
          PARSER = new com.google.protobuf.AbstractParser<Part>() {
        @java.lang.Override
        public Part parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Part(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Part> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Part> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ProtoDTO.Full.Part getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int FULLNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fullName_;
    /**
     * <code>required string fullName = 1;</code>
     * @return Whether the fullName field is set.
     */
    @java.lang.Override
    public boolean hasFullName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string fullName = 1;</code>
     * @return The fullName.
     */
    @java.lang.Override
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fullName = 1;</code>
     * @return The bytes for fullName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULLSIZE_FIELD_NUMBER = 2;
    private int fullSize_;
    /**
     * <code>required uint32 fullSize = 2;</code>
     * @return Whether the fullSize field is set.
     */
    @java.lang.Override
    public boolean hasFullSize() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required uint32 fullSize = 2;</code>
     * @return The fullSize.
     */
    @java.lang.Override
    public int getFullSize() {
      return fullSize_;
    }

    public static final int FULLLIST_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.DoubleList fullList_;
    /**
     * <code>repeated double fullList = 3;</code>
     * @return A list containing the fullList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getFullListList() {
      return fullList_;
    }
    /**
     * <code>repeated double fullList = 3;</code>
     * @return The count of fullList.
     */
    public int getFullListCount() {
      return fullList_.size();
    }
    /**
     * <code>repeated double fullList = 3;</code>
     * @param index The index of the element to return.
     * @return The fullList at the given index.
     */
    public double getFullList(int index) {
      return fullList_.getDouble(index);
    }

    public static final int PART_FIELD_NUMBER = 4;
    private ProtoDTO.Full.Part part_;
    /**
     * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
     * @return Whether the part field is set.
     */
    @java.lang.Override
    public boolean hasPart() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
     * @return The part.
     */
    @java.lang.Override
    public ProtoDTO.Full.Part getPart() {
      return part_ == null ? ProtoDTO.Full.Part.getDefaultInstance() : part_;
    }
    /**
     * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
     */
    @java.lang.Override
    public ProtoDTO.Full.PartOrBuilder getPartOrBuilder() {
      return part_ == null ? ProtoDTO.Full.Part.getDefaultInstance() : part_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFullName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFullSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPart().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fullName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, fullSize_);
      }
      for (int i = 0; i < fullList_.size(); i++) {
        output.writeDouble(3, fullList_.getDouble(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(4, getPart());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fullName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, fullSize_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getFullListList().size();
        size += dataSize;
        size += 1 * getFullListList().size();
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPart());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoDTO.Full)) {
        return super.equals(obj);
      }
      ProtoDTO.Full other = (ProtoDTO.Full) obj;

      if (hasFullName() != other.hasFullName()) return false;
      if (hasFullName()) {
        if (!getFullName()
            .equals(other.getFullName())) return false;
      }
      if (hasFullSize() != other.hasFullSize()) return false;
      if (hasFullSize()) {
        if (getFullSize()
            != other.getFullSize()) return false;
      }
      if (!getFullListList()
          .equals(other.getFullListList())) return false;
      if (hasPart() != other.hasPart()) return false;
      if (hasPart()) {
        if (!getPart()
            .equals(other.getPart())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFullName()) {
        hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFullName().hashCode();
      }
      if (hasFullSize()) {
        hash = (37 * hash) + FULLSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getFullSize();
      }
      if (getFullListCount() > 0) {
        hash = (37 * hash) + FULLLIST_FIELD_NUMBER;
        hash = (53 * hash) + getFullListList().hashCode();
      }
      if (hasPart()) {
        hash = (37 * hash) + PART_FIELD_NUMBER;
        hash = (53 * hash) + getPart().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoDTO.Full parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoDTO.Full parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoDTO.Full parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoDTO.Full parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoDTO.Full parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoDTO.Full parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoDTO.Full parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoDTO.Full parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoDTO.Full parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoDTO.Full parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoDTO.Full parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoDTO.Full parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoDTO.Full prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.sberbank.jmh.Full}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.sberbank.jmh.Full)
        ProtoDTO.FullOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoDTO.internal_static_ru_sberbank_jmh_Full_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoDTO.internal_static_ru_sberbank_jmh_Full_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoDTO.Full.class, ProtoDTO.Full.Builder.class);
      }

      // Construct using ru.sberbank.jmh.dto.ProtoDTO.Full.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPartFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fullName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fullSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fullList_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (partBuilder_ == null) {
          part_ = null;
        } else {
          partBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoDTO.internal_static_ru_sberbank_jmh_Full_descriptor;
      }

      @java.lang.Override
      public ProtoDTO.Full getDefaultInstanceForType() {
        return ProtoDTO.Full.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoDTO.Full build() {
        ProtoDTO.Full result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoDTO.Full buildPartial() {
        ProtoDTO.Full result = new ProtoDTO.Full(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullName_ = fullName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fullSize_ = fullSize_;
          to_bitField0_ |= 0x00000002;
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          fullList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.fullList_ = fullList_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (partBuilder_ == null) {
            result.part_ = part_;
          } else {
            result.part_ = partBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoDTO.Full) {
          return mergeFrom((ProtoDTO.Full)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoDTO.Full other) {
        if (other == ProtoDTO.Full.getDefaultInstance()) return this;
        if (other.hasFullName()) {
          bitField0_ |= 0x00000001;
          fullName_ = other.fullName_;
          onChanged();
        }
        if (other.hasFullSize()) {
          setFullSize(other.getFullSize());
        }
        if (!other.fullList_.isEmpty()) {
          if (fullList_.isEmpty()) {
            fullList_ = other.fullList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFullListIsMutable();
            fullList_.addAll(other.fullList_);
          }
          onChanged();
        }
        if (other.hasPart()) {
          mergePart(other.getPart());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFullName()) {
          return false;
        }
        if (!hasFullSize()) {
          return false;
        }
        if (!hasPart()) {
          return false;
        }
        if (!getPart().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoDTO.Full parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoDTO.Full) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fullName_ = "";
      /**
       * <code>required string fullName = 1;</code>
       * @return Whether the fullName field is set.
       */
      public boolean hasFullName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string fullName = 1;</code>
       * @return The fullName.
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fullName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fullName = 1;</code>
       * @return The bytes for fullName.
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fullName = 1;</code>
       * @param value The fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fullName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fullName = 1;</code>
       * @param value The bytes for fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }

      private int fullSize_ ;
      /**
       * <code>required uint32 fullSize = 2;</code>
       * @return Whether the fullSize field is set.
       */
      @java.lang.Override
      public boolean hasFullSize() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required uint32 fullSize = 2;</code>
       * @return The fullSize.
       */
      @java.lang.Override
      public int getFullSize() {
        return fullSize_;
      }
      /**
       * <code>required uint32 fullSize = 2;</code>
       * @param value The fullSize to set.
       * @return This builder for chaining.
       */
      public Builder setFullSize(int value) {
        bitField0_ |= 0x00000002;
        fullSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 fullSize = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fullSize_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList fullList_ = emptyDoubleList();
      private void ensureFullListIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          fullList_ = mutableCopy(fullList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @return A list containing the fullList.
       */
      public java.util.List<java.lang.Double>
          getFullListList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(fullList_) : fullList_;
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @return The count of fullList.
       */
      public int getFullListCount() {
        return fullList_.size();
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @param index The index of the element to return.
       * @return The fullList at the given index.
       */
      public double getFullList(int index) {
        return fullList_.getDouble(index);
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @param index The index to set the value at.
       * @param value The fullList to set.
       * @return This builder for chaining.
       */
      public Builder setFullList(
          int index, double value) {
        ensureFullListIsMutable();
        fullList_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @param value The fullList to add.
       * @return This builder for chaining.
       */
      public Builder addFullList(double value) {
        ensureFullListIsMutable();
        fullList_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @param values The fullList to add.
       * @return This builder for chaining.
       */
      public Builder addAllFullList(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureFullListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fullList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double fullList = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullList() {
        fullList_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private ProtoDTO.Full.Part part_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoDTO.Full.Part, ProtoDTO.Full.Part.Builder, ProtoDTO.Full.PartOrBuilder> partBuilder_;
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       * @return Whether the part field is set.
       */
      public boolean hasPart() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       * @return The part.
       */
      public ProtoDTO.Full.Part getPart() {
        if (partBuilder_ == null) {
          return part_ == null ? ProtoDTO.Full.Part.getDefaultInstance() : part_;
        } else {
          return partBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      public Builder setPart(ProtoDTO.Full.Part value) {
        if (partBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          part_ = value;
          onChanged();
        } else {
          partBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      public Builder setPart(
          ProtoDTO.Full.Part.Builder builderForValue) {
        if (partBuilder_ == null) {
          part_ = builderForValue.build();
          onChanged();
        } else {
          partBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      public Builder mergePart(ProtoDTO.Full.Part value) {
        if (partBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              part_ != null &&
              part_ != ProtoDTO.Full.Part.getDefaultInstance()) {
            part_ =
              ProtoDTO.Full.Part.newBuilder(part_).mergeFrom(value).buildPartial();
          } else {
            part_ = value;
          }
          onChanged();
        } else {
          partBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      public Builder clearPart() {
        if (partBuilder_ == null) {
          part_ = null;
          onChanged();
        } else {
          partBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      public ProtoDTO.Full.Part.Builder getPartBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPartFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      public ProtoDTO.Full.PartOrBuilder getPartOrBuilder() {
        if (partBuilder_ != null) {
          return partBuilder_.getMessageOrBuilder();
        } else {
          return part_ == null ?
              ProtoDTO.Full.Part.getDefaultInstance() : part_;
        }
      }
      /**
       * <code>required .ru.sberbank.jmh.Full.Part part = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoDTO.Full.Part, ProtoDTO.Full.Part.Builder, ProtoDTO.Full.PartOrBuilder>
          getPartFieldBuilder() {
        if (partBuilder_ == null) {
          partBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoDTO.Full.Part, ProtoDTO.Full.Part.Builder, ProtoDTO.Full.PartOrBuilder>(
                  getPart(),
                  getParentForChildren(),
                  isClean());
          part_ = null;
        }
        return partBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.sberbank.jmh.Full)
    }

    // @@protoc_insertion_point(class_scope:ru.sberbank.jmh.Full)
    private static final ProtoDTO.Full DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoDTO.Full();
    }

    public static ProtoDTO.Full getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Full>
        PARSER = new com.google.protobuf.AbstractParser<Full>() {
      @java.lang.Override
      public Full parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Full(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Full> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Full> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoDTO.Full getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sberbank_jmh_Full_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sberbank_jmh_Full_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sberbank_jmh_Full_Part_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sberbank_jmh_Full_Part_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\017ru.sberbank.jmh\"\244\001\n\004Full\022\020" +
      "\n\010fullName\030\001 \002(\t\022\020\n\010fullSize\030\002 \002(\r\022\020\n\010fu" +
      "llList\030\003 \003(\001\022(\n\004part\030\004 \002(\0132\032.ru.sberbank" +
      ".jmh.Full.Part\032<\n\004Part\022\020\n\010partName\030\001 \002(\t" +
      "\022\020\n\010partSize\030\002 \002(\001\022\020\n\010partList\030\003 \003(\rB\nB\010" +
      "ProtoDTO"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_sberbank_jmh_Full_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sberbank_jmh_Full_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sberbank_jmh_Full_descriptor,
        new java.lang.String[] { "FullName", "FullSize", "FullList", "Part", });
    internal_static_ru_sberbank_jmh_Full_Part_descriptor =
      internal_static_ru_sberbank_jmh_Full_descriptor.getNestedTypes().get(0);
    internal_static_ru_sberbank_jmh_Full_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sberbank_jmh_Full_Part_descriptor,
        new java.lang.String[] { "PartName", "PartSize", "PartList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
